# Define your Device Path
DEVICE_PATH := device/brand/codename

# Allow Missing Dep
ALLOW_MISSING_DEPENDENCIES := true

# Architecture
TARGET_ARCH := 
TARGET_ARCH_VARIANT := 
TARGET_CPU_ABI := 
TARGET_CPU_ABI2 := 
TARGET_CPU_VARIANT := 
TARGET_CPU_VARIANT_RUNTIME := 

# Include this only if TARGET_ARCH is amr64
TARGET_2ND_ARCH := 
TARGET_2ND_ARCH_VARIANT := 
TARGET_2ND_CPU_ABI := 
TARGET_2ND_CPU_ABI2 := 
TARGET_2ND_CPU_VARIANT := 
TARGET_2ND_CPU_VARIANT_RUNTIME := 

# If arm and uses 64-bit Binder
TARGET_USES_64_BIT_BINDER := true

# Bootloader Name
TARGET_BOOTLOADER_BOARD_NAME :=

# Kernel Identifier - Keep Blank if it doesn't exist or just don't inlcude the flags
BOARD_BOOTIMG_HEADER_VERSION :=
BOARD_KERNEL_BASE := 
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_PAGESIZE :=
BOARD_RAMDISK_OFFSET :=
BOARD_KERNEL_TAGS_OFFSET :=
BOARD_KERNEL_IMAGE_NAME :=
BOARD_INCLUDE_DTB_IN_BOOTIMG :=
BOARD_KERNEL_SEPARATED_DTBO :=
TARGET_KERNEL_CONFIG :=
TARGET_KERNEL_SOURCE :=

# MKBOOTIMG Args - No need to put every args, use what you need only
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb $(TARGET_PREBUILT_DTB)

# Kernel - Prebuilt
TARGET_PREBUILT_KERNEL :=
TARGET_PREBUILT_DTB := 
BOARD_PREBUILT_DTBOIMAGE :=

# Copy out error workarounds
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE :=
TARGET_COPY_OUT_VENDOR := true

# Partitions
BOARD_FLASH_BLOCK_SIZE := # $(BOARD_KERNEL_PAGESIZE) * 64
BOARD_RECOVERYIMAGE_PARTITION_SIZE :=
BOARD_HAS_LARGE_FILESYSTEM :=
BOARD_SYSTEMIMAGE_PARTITION_TYPE :=
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE :=

# Super Partitions
BOARD_SUPER_PARTITION_SIZE :=
BOARD_SUPER_PARTITION_GROUPS := SUPER_DUMMY
BOARD_SUPER_DUMMY_PARTITION_LIST :=
BOARD_SUPER_DUMMY_SIZE :=

# Security Patch
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH )

# Platform Version
PLATFORM_VERSION :=99.87.36

# TWRP Configuration, needed more...
TW_THEME := portrait_hdpi
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true